### ISSUE TITLE
How to remove/customize defaul splash screen?

### ISSUE THREAD

**Issue by michael-land** [adafruit/Adafruit_CircuitPython_MatrixPortal#86]
I want to remove the default splash screen (The circuitpython logo and some text on boot) , is it possible?

**Comment by Neradoc** [comment]
What is happening is that displayio inits the display with the REPL by default and displays it first thing before you customize the display.

----

With this library you can try this: get the python version of the library, and look into the matrix.py file. Change this line by adding `auto_refresh=False` in the arguments:
https://github.com/adafruit/Adafruit_CircuitPython_MatrixPortal/blob/fe15f7c93d849b092b112b68e9f645fe76990649/adafruit_matrixportal/matrix.py#L199
Like this:
```py
 self.display = framebufferio.FramebufferDisplay(matrix, rotation=rotation, auto_refresh=False)
```

Then after you have setup your screen in your main code (setting up labels or display.shwo()), change it back with:
```py
matrix.display.auto_refresh = True
```
This should make the display stay off until you turn refresh on (or manually call display.refresh()).
This will not impact what happens when the board reloads the code.

----

Alternatively you could hide the REPL as soon as the display is setup.
With builtin displays you can toy with the `root_group` which contains the logo and the REPL. It's implemented for the Matrix Portal in the absolute latest: https://github.com/adafruit/circuitpython/pull/6595 so if you want to try that version of Circuitpython, you can [grab it from here](https://adafruit-circuit-python.s3.amazonaws.com/index.html?prefix=bin/matrixportal_m4/) and do this as soon as you have setup the Matrix instance. (Or you could add it in matrix.py right after the other line).
```py
matrix.display.root_group.hidden = True
```

**Comment by michael-land** [comment]
It is working like a charm! 🎊 Thank you so much!
