### ISSUE TITLE
MatrixPortal constructor doesn't work with Adafruit Matrix Portal M4 board

### ISSUE THREAD

**Issue by thomaspaulin** [adafruit/Adafruit_CircuitPython_MatrixPortal#96]
I've connected it up to the 64x32 display via a Matrix Portal M4, and I was under the impression, from the guides I read, this should work with the matrixportal library, however when write a two line code.py file as:

```
from adafruit_matrixportal.matrixportal import MatrixPortal
matrix = MatrixPortal()
```

I get an error on the dot matrix display saying "112@ada", vs using the lower level Matrix library (below) which executes as expected:
```
from adafruit_matrixportal.matrix import Matrix
matrix = Matrix()
```

The guides I'm following suggest this is possible so I'm very confused.

The CIRCUITPY lib/ folder is:
```
adafruit_bitmap_font       adafruit_io            adafruit_portalbase
adafruit_bus_device        adafruit_matrixportal  adafruit_requests.mpy
adafruit_display_text      adafruit_minimqtt      neopixel.mpy
adafruit_esp32spi          adafruit_miniqr.mpy    simpleio.mpy
adafruit_fakerequests.mpy  adafruit_pixelbuf.mpy
```

My truncated pip freeze (the request are certilib, requests, and other non-adafruit libs)
```
adafruit-blinka-displayio==1.2.1
adafruit-circuitpython-adafruitio==5.8.1
adafruit-circuitpython-bitmap-font==2.1.1
adafruit-circuitpython-busdevice==5.2.6
adafruit-circuitpython-display-text==3.0.6
adafruit-circuitpython-esp32spi==6.1.3
adafruit-circuitpython-fakerequests==1.0.14
adafruit-circuitpython-matrixportal==3.1.13
```
This was initially run on PyCharm but I've since re-flashed the board and added only the libraries found [on the Adafruit setup guide](https://learn.adafruit.com/adafruit-matrixportal-m4/circuitpython-setup), plus I used a text editor to write the code.py file.

Given the lack of information on-screen it's not apparent whether this is an issue in the library or in my setup.

[The firmware I used was Circuit Python 8.2.9 ](https://downloads.circuitpython.org/bin/matrixportal_m4/en_GB/adafruit-circuitpython-matrixportal_m4-en_GB-8.2.9.uf2) and the [library bundle was for version 8.x](https://github.com/adafruit/Adafruit_CircuitPython_Bundle/releases/download/20240212/adafruit-circuitpython-bundle-8.x-mpy-20240212.zip)

**Comment by FoamyGuy** [comment]
@thomaspaulin can you post a link to the guide page where you you found this code originally?

In order to troubleshoot it will be very helpful to get connected to the serial console of the device so that you can access the full error message. This guide page covers the basic process of getting connected: https://learn.adafruit.com/welcome-to-circuitpython/kattni-connecting-to-the-serial-console 

If you are using pycharm, on Linux or Mac there is a tool called `tio` that can make it easier to connect to the console from directly inside of the terminal in pycharm, that is documented a little bit here: https://learn.adafruit.com/welcome-to-circuitpython/pycharm-and-circuitpython#serial-console-in-the-terminal-pane-3105096 If your on windows there is putty, but I don't know if it's possible to integrate it directly in the terminal in pycharm like tio can.

Please check the serial console and post the full error message.

**Comment by thomaspaulin** [comment]
@FoamyGuy One such example would the [Matrix Portal New Guide Scroller](https://learn.adafruit.com/matrix-portal-new-guide-scroller/code-the-matrix-portal).

However per your suggestion of monitoring the serial monitor, I found it mentioning secrets.py requires at least `ssid` and `password`. Adding these in the format from the above guide fixed my issue, thanks!
